var courseData = [
{
  courseNumber: "Com Sci 35L",
department: "Computer Science",
disHours: 4,
essays: 0,
lecHours: 0,
lecNum: 2,
outHours: 5,
professor: "Zhang, Z.; Eggert, P.R.",
projects: 8,
readWeek: 0,
session: "Fall 2018",
syllabus: "https://web.cs.ucla.edu/classes/fall18/cs35L/",
units: 3
},
{
  courseNumber: "Com Sci 35L",
  department: "Computer Science",
disHours: 4,
essays: 0,
lecHours: 0,
lecNum: 2,
outHours: 6,
professor: "Kabre, A.; Eggert, P.R.",
projects: 9,
readWeek: 0,
session: "Fall 2017",
syllabus: "http://web.cs.ucla.edu/classes/fall17/cs35L/index.html",
units: 3
},
{
  courseNumber: "Com Sci M51A",
  department: "Computer Science",
  disHours: 2,
  essays: 0,
  lecHours: 4,
  lecNum: 2,
  outHours: 6,
  professor: "Mcilhenny, R.D.",
  projects: 0,
  readWeek: 0,
  session: "Fall 2018",
  syllabus: "https://ccle.ucla.edu/pluginfile.php/2379836/local_ucla_syllabus/syllabus/52870/syllabus_cs_m51a_ee_m16%20(Last%20modified%2018-11-7--15-28).pdf",
  units: 4
},
{
  courseNumber: "Com Sci M51A",
  department: "Computer Science",
  disHours: 2,
  essays: 0,
  lecHours: 4,
  lecNum: 2,
  outHours: 6,
  professor: "Ercegovac, M.D.",
  projects: 0,
  readWeek: 0,
  session: "Fall 2018",
  syllabus: "http://web.cs.ucla.edu/~milos/CSM51A-F18-Syllabus.pdf",
  units: 4
},
{
  courseNumber: "Com Sci M51A",
  department: "Computer Science",
  disHours: 2,
  essays: 0,
  lecHours: 4,
  lecNum: 2,
  outHours: 6,
  professor: "Potkonjak, M.",
  projects: 0,
  readWeek: 0,
  session: "Winter 2019",
  syllabus: "Not Available Yet",
  units: 4
},
{
  courseNumber: "Musclg 70",
  department: "Musicology",
  disHours: 1,
  essays: 2,
  lecHours: 4,
  lecNum: 2,
  outHours: 6,
  professor: "Knapp, R.L.",
  projects: 0,
  readWeek: 35,
  session: "Fall 2018",
  syllabus: "Not Available Yet",
  units: 5
},
{
  courseNumber: "Com Sci 188",
  department: "Computer Science",
  disHours: 2,
  essays: 0,
  lecHours: 4,
  lecNum: 2,
  outHours: 6,
  professor: "Lee, U.",
  projects: 4,
  readWeek: 20,
  session: "Fall 2018",
  syllabus: "https://docs.google.com/document/d/1T-vRhg7h20Y47Kc47UFKLTAfCeUpuyNiraQVp_Mqzwo/edit",
  units: 4
},
{
  courseNumber: "Chin 50",
  department: "Chinese",
  disHours: 1,
  essays: 3,
  lecHours: 3,
  lecNum: 2,
  outHours: 6,
  professor: "Li, M.",
  projects: 0,
  readWeek: 40,
  session: "Fall 2018",
  syllabus: "https://www.coursehero.com/file/22687396/CHIN-50-Syllabus-Spring-2017/",
  units: 5
},
{
  courseNumber: "Stats 100A",
  department: "Statistics",
  disHours: 2,
  essays: 0,
  lecHours: 3,
  lecNum: 3,
  outHours: 7,
  professor: "Sanchez, J.",
  projects: 0,
  readWeek: 0,
  session: "Summer 2018",
  syllabus: "http://www.stat.ucla.edu/~nchristo/statistics100A/syllabus100a_sum15.pdf",
  units: 4
},
{
  courseNumber: "Stats 100A",
  department: "Statistics",
  disHours: 1,
  essays: 0,
  lecHours: 2.5,
  lecNum: 2,
  outHours: 7,
  professor: "Paik Schoenberg, F",
  projects: 0,
  readWeek: 0,
  session: "Fall 2018",
  syllabus: "http://www.stat.ucla.edu/~frederic/100a/F18/100asyllabusF18.html",
  units: 4
}
]
