
  var courseData = [
{
  courseNumber: "Com Sci 35L",
  title: "Software Construction Laboratory",
  department: "Computer Science",
  professor:"Zhang, Z.; Eggert, P.R.",
  session:"Fall 2018",
  units: 3,
  lecHours:0,
  lecNum: 2,
  disHours:4,
  outHours:5,
  projects: 10,
  essays: 0,
  readWeek: 0,
  syllabus: "https://web.cs.ucla.edu/classes/fall18/cs35L/"
},
{
  courseNumber: "Com Sci 35L",
  title: "Software Construction Laboratory",
  department: "Computer Science",
  professor:"Kabre, A.; Eggert, P.R.",
  session:"Fall 2017",
  units: 3,
  lecHours:0,
  lecNum: 2,
  disHours:4,
  outHours:5,
  projects: 10,
  essays: 0,
  readWeek: 0,
  syllabus: "http://web.cs.ucla.edu/classes/fall17/cs35L/index.html"
},
{
  courseNumber: "Com Sci M51A",
  title: "Logic Design of Digital Systems",
  department: "Computer Science",
  professor:"Mcilhenny, R.D.",
  session:"Fall 2018",
  units: 4,
  lecHours:4,
  lecNum: 2,
  disHours:2,
  outHours:6,
  projects: 0,
  essays: 0,
  readWeek: 0,
  syllabus: "https://ccle.ucla.edu/pluginfile.php/2379836/local_ucla_syllabus/syllabus/52870/syllabus_cs_m51a_ee_m16%20(Last%20modified%2018-11-7--15-28).pdf"
},
{
  courseNumber: "Com Sci M51A",
  title: "Logic Design of Digital Systems",
  department: "Computer Science",
  professor:"Ercegovac, M.D.",
  session:"Fall 2018",
  units: 4,
  lecHours:4,
  lecNum: 2,
  disHours:2,
  outHours:6,
  projects: 0,
  essays: 0,
  readWeek: 0,
  syllabus: "http://web.cs.ucla.edu/~milos/CSM51A-F18-Syllabus.pdf"
},
{
  courseNumber: "Com Sci M51A",
  title: "Logic Design of Digital Systems",
  department: "Computer Science",
  professor:"Potkonjak, M.",
  session:"Winter 2019",
  units: 4,
  lecHours:4,
  lecNum: 2,
  disHours:2,
  outHours:6,
  projects: 0,
  essays: 0,
  readWeek: 0,
  syllabus: "Not Available Yet"
},
{
  courseNumber: "Musclg 70",
  title: "Beethoven",
  department: "Musicology",
  professor:"Knapp, R.L.",
  session:"Fall 2018",
  units: 5,
  lecHours:4,
  lecNum: 2,
  disHours:1,
  outHours:6,
  projects: 0,
  essays: 2,
  readWeek: 35,
  syllabus: "Not Available Yet"
},
{
  courseNumber: "Com Sci 188",
  title: "Special Courses in Computer Science",
  department: "Computer Science",
  professor:"Lee, U.",
  session:"Fall 2018",
  units: 4,
  lecHours:4,
  lecNum: 2,
  disHours:2,
  outHours:6,
  projects: 4,
  essays: 0,
  readWeek: 20,
  syllabus: "https://docs.google.com/document/d/1T-vRhg7h20Y47Kc47UFKLTAfCeUpuyNiraQVp_Mqzwo/edit"
},
{
  courseNumber: "Chin 50",
  title: "Chinese Civilization",
  department: "Chinese",
  professor:"Li, M.",
  session:"Fall 2018",
  units: 5,
  lecHours:3,
  lecNum: 2,
  disHours:1,
  outHours:6,
  projects: 0,
  essays: 3,
  readWeek: 40,
  syllabus: "https://www.coursehero.com/file/22687396/CHIN-50-Syllabus-Spring-2017/"
},
{
  courseNumber: "Stats 100A",
  title: "Introduction to Probability",
  department: "Statistics",
  professor:"Sanchez, J.",
  session:"Summer 2018",
  units: 4,
  lecHours:3,
  lecNum: 3,
  disHours:2,
  outHours:7,
  projects: 0,
  essays: 0,
  readWeek: 0,
  syllabus: "http://www.stat.ucla.edu/~nchristo/statistics100A/syllabus100a_sum15.pdf"
},
{
  courseNumber: "Stats 100A",
  title: "Introduction to Probability",
  department: "Statistics",
  professor:"Paik Schoenberg, F",
  session:"Fall 2018",
  units: 4,
  lecHours:2.5,
  lecNum: 2,
  disHours:1,
  outHours:7,
  projects: 0,
  essays: 0,
  readWeek: 0,
  syllabus: "http://www.stat.ucla.edu/~frederic/100a/F18/100asyllabusF18.html"
}
];
